resident-ui/Dockerfile
resident-ui/configure_start.sh
resident-ui/default.conf
resident-ui/download.conf
resident-ui/nginx.conf

added docker file

---

resident-ui/src/app/core/services/loginredirect.service.ts

https://mosip.atlassian.net/browse/MOSIP-26126

login redirect landing page issue fixed

---

resident-ui/src/app/shared/header/header.component.ts

https://mosip.atlassian.net/browse/MOSIP-26144

update demographic page file upload related bug fixes

---

resident-ui/src/app/feature/uinservices/dashboard/dashboard.component.ts

https://mosip.atlassian.net/browse/MOSIP-26974

uinservice landing dashboard redirect to login page

---

resident-ui/src/app/feature/uinservices/lockunlockauth/lockunlockauth.component.ts

https://mosip.atlassian.net/browse/MOSIP-26586

Sending only changed attribute to the api in lock and unlock

---

resident-ui/src/app/app-config.service.ts
resident-ui/src/app/feature/getuin/getuin/getuin.component.html
resident-ui/src/app/feature/getuin/getuin/getuin.component.ts
resident-ui/src/app/feature/verify/verify/verify.component.html
resident-ui/src/app/feature/verify/verify/verify.component.ts

https://mosip.atlassian.net/browse/MOSIP-27692

Automation related changes for captcha configurable

---

resident-ui/src/app/feature/uinservices/dashboard/dashboard.component.ts

https://mosip.atlassian.net/browse/MOSIP-27977

preventing back button in firefox inside uinservices

---

resident-ui/src/app/app-config.service.ts
resident-ui/src/app/feature/uinservices/dashboard/dashboard.component.css
resident-ui/src/app/feature/uinservices/dashboard/dashboard.component.html
resident-ui/src/app/feature/uinservices/personalisedcard/personalisedcard.component.ts
resident-ui/src/app/feature/uinservices/updatedemographic/updatedemographic.component.html
resident-ui/src/app/feature/uinservices/updatedemographic/updatedemographic.component.ts
resident-ui/src/app/shared/header/header.component.css
resident-ui/src/app/shared/header/header.component.html
resident-ui/src/app/shared/header/header.component.ts
resident-ui/src/assets/i18n/hin.json
resident-ui/src/assets/i18n/kan.json
resident-ui/src/assets/i18n/spa.json
resident-ui/src/assets/i18n/tam.json

added multi languages and fixed breaking alignments when using multi languages.

MOSIP-21285 added multi languages

---

resident-ui/src/app/feature/booking/center-selection/center-selection.component.css
resident-ui/src/app/feature/uinservices/viewhistory/viewhistory.component.html
resident-ui/src/app/feature/uinservices/viewhistory/viewhistory.component.ts
resident-ui/src/app/shared/header/header.component.css

In view history page All placeholder now available with multi languages.

MOSIP-28550 added all for multi language.

---

resident-ui/src/app/feature/uinservices/revokevid/revokevid.component.ts
resident-ui/src/app/feature/uinservices/trackservicerequest/trackservicerequest.component.html
resident-ui/src/app/feature/uinservices/trackservicerequest/trackservicerequest.component.ts
resident-ui/src/app/feature/uinservices/viewhistory/viewhistory.component.html

[MOSIP-28596] - added id's in view history page buttons.
[MOSIP-28610] - after download VID card from track service request button will be disable from UI end.
[MOSIP-28596]: https://mosip.atlassian.net/browse/MOSIP-28596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOSIP-28610]: https://mosip.atlassian.net/browse/MOSIP-28610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOSIP-28596, MOSIP-28610 fixed two issues

---

resident-ui/src/app/shared/dialog/dialog.component.html
resident-ui/src/app/shared/dialog/dialog.component.ts

1. success message popup ok button back ground color changed to green.
2. removed to navigating to UIN dashboard when click the ok button

Fixed success popup issues

---

.github/workflows/push-trigger.yml
.github/workflows/release-changes.yml

To fix sonar job failures
[MOSIP-25631]
[MOSIP-25631]: https://mosip.atlassian.net/browse/MOSIP-25631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOSIP-29164] Updated workflows as per reusable templates

---

resident-ui/src/app/feature/booking/center-selection/center-selection.component.html
resident-ui/src/app/feature/uinservices/dashboard/dashboard.component.css
resident-ui/src/app/feature/uinservices/dashboard/dashboard.component.html
resident-ui/src/app/shared/dialog/dialog.component.css

MOSIP-25460 - showing cursor for UIN services heading,
MOSIP-27938 - Changed registration center details alignment.

MOSIP-25460 MOSIP-27938 

---

.github/workflows/push-trigger.yml

[MOSIP-25631]
[MOSIP-25631]: https://mosip.atlassian.net/browse/MOSIP-25631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOSIP-29164] Updated push-trigger.yml

---

.github/workflows/push-trigger.yml

[MOSIP-25631]
[MOSIP-25631]: https://mosip.atlassian.net/browse/MOSIP-25631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOSIP-29164] removed publish-to-nexus for residenttest

---

resident-ui/src/app/feature/booking/center-selection/center-selection.component.css
resident-ui/src/app/feature/dashboard/dashboard/dashboard.component.css
resident-ui/src/app/feature/dashboard/dashboard/dashboard.component.html
resident-ui/src/app/feature/dashboard/dashboard/dashboard.component.ts
resident-ui/src/app/feature/uinservices/revokevid/revokevid.component.ts
resident-ui/src/app/feature/uinservices/updatedemographic/updatedemographic.component.ts
resident-ui/src/app/feature/verify/verify/verify.component.css
resident-ui/src/app/feature/verify/verify/verify.component.html
resident-ui/src/app/feature/verify/verify/verify.component.ts

and fixed alignment issues in verifying channel number and the main dashboard

MOSIP-30209 sending audit log data after click confirmation button.

---

resident-ui/src/app/core/services/data-storage.service.ts
resident-ui/src/app/feature/dashboard/dashboard/dashboard.component.css
resident-ui/src/app/feature/dashboard/dashboard/dashboard.component.html
resident-ui/src/app/feature/uinservices/updatedemographic/updatedemographic.component.html
resident-ui/src/app/feature/uinservices/updatedemographic/updatedemographic.component.ts

Removed empty space in the main dashboard.

MOSIP-30268 using preferred lang Api for preferred language dropdown

---

residenttest/src/main/java/io/mosip/testrig/residentui/testcase/GetMyUIN.java
residenttest/src/main/java/io/mosip/testrig/residentui/utility/BaseClass.java
residenttest/src/main/resources/config/Kernel.properties
residenttest/src/main/resources/testngFile/testng.xml

Added more wait in get my uin so we can get more time to download the uin card also we added the priority to the get my uin class and Remove commented  code that we are not using again

MOSIP-31229

---

residenttest/src/main/java/io/mosip/testrig/residentui/kernel/util/ConfigManager.java
residenttest/src/main/java/io/mosip/testrig/residentui/testcase/GetInformation.java
residenttest/src/main/java/io/mosip/testrig/residentui/testcase/LoginTest.java
residenttest/src/main/java/io/mosip/testrig/residentui/utility/Commons.java
residenttest/src/main/java/io/mosip/testrig/residentui/utility/EmailableReport.java
residenttest/src/main/java/io/mosip/testrig/residentui/utility/ResidentBaseClass.java
residenttest/src/main/java/io/mosip/testrig/residentui/utility/TestRunner.java
residenttest/src/main/resources/config/Kernel.properties
residenttest/src/main/resources/config/Kernel_dev2.properties
residenttest/src/main/resources/config/Kernel_qa-trinity.properties

We write the code to take a screenshot and attack to testng report . Also write a code to run single scenarios through kernel

MOSIP-31296

---

residenttest/src/main/java/io/mosip/testrig/residentui/testcase/UpdateMyData.java
residenttest/src/main/java/io/mosip/testrig/residentui/utility/BaseClass.java

Add environment support lang id's

MOSIP-31332

---

resident-ui/src/app/feature/uinservices/dashboard/dashboard.component.css
resident-ui/src/app/feature/uinservices/trackservicerequest/trackservicerequest.component.css
resident-ui/src/app/feature/uinservices/updatedemographic/updatedemographic.component.html
resident-ui/src/app/feature/uinservices/updatedemographic/updatedemographic.component.ts
resident-ui/src/app/feature/uinservices/viewhistory/viewhistory.component.css
resident-ui/src/app/feature/uinservices/viewhistory/viewhistory.component.html
resident-ui/src/app/feature/uinservices/viewhistory/viewhistory.component.ts
resident-ui/src/styles.css

Resolved alignment issues in update my data, track service, view my history pages.
Resolved keyboard hiding view issue in update my data page

MOSIP-32863 MOSIP-32845 MOSIP-32848 MOSIP-32849

---

resident-ui/src/app/feature/uinservices/lockunlockauth/lockunlockauth.component.css
resident-ui/src/app/feature/uinservices/lockunlockauth/lockunlockauth.component.html
resident-ui/src/app/feature/uinservices/lockunlockauth/lockunlockauth.component.ts
resident-ui/src/app/feature/uinservices/updatedemographic/updatedemographic.component.html
resident-ui/src/app/feature/verify/verify/verify.component.html
resident-ui/src/app/shared/dialog/dialog.component.css

Resolved alignment issues in secure my ID and verify email and phone number pages

MOSIP-32847 MOSIP-32936 MOSIP-32989 MOSIP-32994

---

uitest-resident/src/main/java/io/mosip/testrig/residentui/testcase/ShareMyData.java

As we change the id of name to fullName as developer change it in ui

MOSIP-35558

---

uitest-resident/src/main/java/io/mosip/testrig/residentui/fw/util/AdminTestUtil.java
uitest-resident/src/main/java/io/mosip/testrig/residentui/testcase/UpdateMyData.java

In update my name we are handling first name last name and full name according to the env .

MOSIP-35896

---

uitest-resident/src/main/java/io/mosip/testrig/residentui/testcase/LoginTest.java

Sometime taking  to load login page that a time it's going into else condition so add some different logic there

MOSIP-35988

---

uitest-resident/Dockerfile

Update Dockerfile to Use Java 21 for  resident ui automation

MOSIP-36166

---

.github/workflows/push-trigger.yml
residenttest/pom.xml

MOSIP-39395 update the pom.xml

MOSIP-39395 update the pom.xml
